# Generated by Django 4.2.29 on 2026-04-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
    ]
